[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True

[mypy-app.api.*]
ignore_errors = True

[mypy-app.application.use_cases.*]
ignore_errors = True

[mypy-app.domain.models.*]
ignore_errors = True

[mypy-app.infrastructure.database.*]
ignore_errors = True

[mypy-app.core.config.*]
ignore_errors = True

[mypy-app.tests.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True

